---
- hosts: all
  tasks:
  - name: download transaction_list
    block:
    - file:
        state: directory
        path: /home/ansible/lab-error-handling
        mode: '0755'
    - get_url:
          url: https://bit.ly/3dtJtR7
          dest: /home/ansible/lab-error-handling/transaction_list
    - replace:
        path: /home/ansible/lab-error-handling/transaction_list
        regexp: "#BLANKLINE"
        replace: '\n'
    - debug: msg="File downloaded successfully"
    rescue: 
    - debug: msg="Site appears to be down. Try again later."
    always:
    - debug: msg="attempt completed"